### PR TITLE
fix(transformation): update crawler algorithm

### PR DESCRIPTION
**Pull request by gmenih**
There was a bug in the builtin transformer `replace-node`. If the `replaceWith` contained a the value of `matchWith`, it would fall into an infinite loop and throw with `RangeError: Maximum call stack size exceeded`.

### CODE REVIEW

**Comment by tusharmath** [comment]
Thanks a ton @gmenih341 for reporting the issue and also providing its fix!


Quick thing though, I think a better solution would be for the transformer to not crawl the nodes that have already been replaced.

Look at —
https://github.com/tusharmath/ts-codemod/blob/master/src/Transformation.ts#L18

A change such as the following might be a more generic solution.
```ts
public forEach = (input: ts.Node): ts.VisitResult<ts.Node> => {
    const node = this.visit(input)

    // if nothing changed, go deeper.
    if (node === input) {
      return node instanceof Array
        ? node.map(_ => ts.visitEachChild(_, this.forEach, this.ctx))
        : ts.visitEachChild(node, this.forEach, this.ctx)
    }

    // don't search in replaced node
    return node
  }
```

Do you mind updating your PR with these changes?

**Review by tusharmath — CHANGES_REQUESTED** [review]
Thanks a ton @gmenih341 for reporting the issue and also providing its fix!


Quick thing though, I think a better solution would be for the transformer to not crawl the nodes that have already been replaced.

Look at —
https://github.com/tusharmath/ts-codemod/blob/master/src/Transformation.ts#L18

A change such as the following might be a more generic solution.
```ts
public forEach = (input: ts.Node): ts.VisitResult<ts.Node> => {
    const node = this.visit(input)

    // if nothing changed, go deeper.
    if (node === input) {
      return node instanceof Array
        ? node.map(_ => ts.visitEachChild(_, this.forEach, this.ctx))
        : ts.visitEachChild(node, this.forEach, this.ctx)
    }

    // don't search in replaced node
    return node
  }
```

Do you mind updating your PR with these changes?

**Comment by gmenih341** [comment]
@tusharmath thanks for pointing out where to fix this properly. I considered it to be a bug only for `replace-node`. I'll push a proper fix in a bit :)

**Review by tusharmath — APPROVED** [review]

**Comment by tusharmath** [comment]
thanks!

**Pull request merged**
